#faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada
n = int(input('Qual número inteiro você quer saber a tabuada? '))
#t = (n*1); 2 = (n2) ; t3 = (n*3) ; t4 = (n*4) ; t5 = (n*5) ; t6 = (n*6) ; t7 = (n*7) ; t8 = (n*8) ; t9 = (n*9) ; t10 = (n*10)
#print( 'A tabuada de', n, 'é:\n', n,'X 01 = ', t,'\n', n, 'X 2 = ',2, '\n', n, 'X 03 = ', t3, '\n', n,'X 04 = ', t4, '\n', n, 'X 05 = ', t5, '\n', n,'X 06 = ', t6, '\n', n,'X 07 = ', t7, '\n', n,'X 08 = ', t8, '\n', n,'X 09 = ', t9, '\n', n,'X 10 = ', t10)
print('-' * 12)
print('{} X {:2} = {: 2}'.format(n, 1, n*1))
print('{} X {:2} = {: 2}'.format(n, 2, n*2))
print('{} X {:2} = {: 2}'.format(n, 3, n*3))
print('{} X {:2} = {: 2}'.format(n, 4, n*4))
print('{} X {:2} = {: 2}'.format(n, 5, n*5))
print('{} X {:2} = {: 2}'.format(n, 6, n*6))
print('{} X {:2} = {: 2}'.format(n, 7, n*7))
print('{} X {:2} = {: 2}'.format(n, 8, n*8))
print('{} X {:2} = {: 2}'.format(n, 9, n*9))
print('{} X {:2} = {: 2}'.format(n, 10, n*10))
print('_' * 12)
